version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: moviesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    command: pnpm run start:dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db_data:
